### ISSUE TITLE
No Advanced options set, so cannot change service connection...

### ISSUE THREAD

**Issue by Stoffe** [RazorSPoint/azure-devops-azure-policy-extension#11] opened 2020-03-12 11:44 UTC
Only see a button called "Authorize" there is no drop down or any advanced options and since I.
1. Do not want to use my personal account to login to Azure.
2. Do not have access with my personal account as its not the same I use for Azure.

How come you say there is an advanced options and manage connections but I cannot see this in my deployment task?

**Comment by SebastianSchuetze** [comment] 2020-03-13 16:39
Hi @Stoffe this is actually not a feature of the task, but an integrated control within Azure DevOps. What you are referring to is probably this here

![image](https://user-images.githubusercontent.com/7256168/76640921-0a6ea080-6551-11ea-9408-4a35dac6b656.png)

I don't know why you do not see this, but you have to authorize it with your account. But in the end your account is not used. It is used to create a service principal on your behalf, which is then used to connect to Azure.

If you do not have Azure, then you have to use the advanced setup in the service connection configuration of your project. 
Check the following documentation.
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-with-an-existing-service-principal

If you create a connection beforehand, then you should be able to start using it in the task.

But other than that, it does not seem to be a bug and caused by the task itself. Closing this, but please if you still think that it is a problem of a task, then you can answer here. :-)

**Closed as completed by SebastianSchuetze** 2020-03-13 16:39 UTC
Labels: question, Azure Policy task
